apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: docker.io/johnd0es/pingpong:3.0
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "postgres://pingpong:pingpong@postgres-0.postgres.exercises.svc.cluster.local:5432/pingpong"
          ports:
            - containerPort: 3000
