apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-image-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /data/todo-image
