apiVersion: apps/v1
kind: Deployment
metadata:
  name: logreader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logreader
  template:
    metadata:
      labels:
        app: logreader
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-claim
      containers:
        - name: logreader
          image: johnd0es/logreader:1.6
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/data
