apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-claim
      containers:
        - name: logoutput
          image: johnd0es/logoutput:1.7
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/data
          ports:
            - containerPort: 3000
