apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
  namespace: exercises
spec:
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: logoutput-config
            items:
              - key: information.txt
                path: information.txt

      containers:
        - name: logoutput
          image: johnd0es/logoutput:2.1

          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-config
                  key: MESSAGE

          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/config
              readOnly: true
