apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-cache
  labels:
    app: image-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-cache
  template:
    metadata:
      labels:
        app: image-cache
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3d-k3s-agent-0
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-claim
      containers:
        - name: image-cache
          image: johnd0es/image-cache:1.13
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "128Mi"
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/data
